### DISCUSSION TITLE
dials.image_viewer: image should be shown in image frame

### DISCUSSION THREAD

**Discussion by graeme-winter** [dials/dials#1358] [General]
https://github.com/dials/dials/pull/1182 introduced a "bug / feature" that single panel images are now shown at a jaunty angle if they have been refined, which is probably not what we want in an image viewer. 

In fact, to me it would seem canonical that an image viewer shows the image in the image coordinate frame not the laboratory frame. As an example:

![Screenshot 2020-07-27 at 15 04 30](https://user-images.githubusercontent.com/1241716/88551571-e781ec00-d01a-11ea-9ff9-f243942ae8e5.png)

It is also known that the shoeboxes are not plotted in this rotated frame - #1189 - and I really see no benefit in what is shown here for a single panel. `dials.show` is a _much better_ way of showing that the detector is misaligned and gives actual data not just some dodgy image which confuses users:

```
Detector:
Panel:
  name: /entry/instrument/detector
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.075,0.075}
  image_size: {4148,4362}
  trusted_range: {-1,53338}
  thickness: 0.45
  material: Si
  mu: 1.41469
  gain: 1
  pedestal: 0
  fast_axis: {0.999977,0.00662009,-0.00137573}
  slow_axis: {0.00661354,-0.999967,-0.00471405}
  origin: {-156.829,166.876,-138.646}
  distance: 139.65
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 1.41469
    t0: 0.45
```

I've previously stated "I’m just asking to be able to have the original behaviour, not to remove the opportunity to see your detector slightly misaligned"

We could have a vote on this 🙂  - if you agree that the default should be image frame => 👍  i.e. revert to previous behaviour. If you feel that it should be shown in some lab-frame-like system then 👎  would capture this nicely.
