### ISSUE TITLE
Inscribed resolution wrong in dials.show

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#348]
```
Experiment 0:
Detector:
Panel:
  name: Panel
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.172,0.172}
  image_size: {2463,2527}
  trusted_range: {-1,489996}
  thickness: 1
  material: Si
  mu: 3.92191
  gain: 1
  fast_axis: {0.999848,0.0134404,0.0110946}
  slow_axis: {0.0135327,-0.999874,-0.00829228}
  origin: {-209.606,203.601,-300.841}

Max resolution (at corners): 1.252934
Max resolution (inscribed):  1.768631
```

however max inscribed resolution around 1.64
