### ISSUE TITLE
precommitbx doesn't upgrade

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#880]
Had issues running, think related to install on RHEL6/running on 7
```
ImportError: libffi.so.5: cannot open shared object file: No such file or directory
```
`libtbx.precommit` shows:
```
Precommit Python: 3.7.3 (expected: 3.7.4)
Precommitbx: 1.0.0

Repositories:
  annlib.........: (no pre-commit hooks)
  boost..........: (no pre-commit hooks)
  cbflib.........: (no pre-commit hooks)
  dials..........: pre-commit installed
  dials_regression: (no pre-commit hooks)
  dxtbx..........: pre-commit installed
  xia2...........: pre-commit installed

To install pre-commit hooks run libtbx.precommit install
```
so the version is out of date anyway. Ran `libtbx.precommit install` and it... showed the same message. `installer.py:main` calls `install_python` if the version is mismatched, but `install_python` _only_ checks for the presence of the executable `python3`. I tried to fix this in https://github.com/ndevenish/dials/commit/9f509a2f25483ff0a58f9901ea843753d6146488 but install failed with 
```
Python has not picked up correct SQLite headers
```
At this point I went 🤷‍♂ and deleted the python install to start from scratch.
